Está inportanto a biblioteca numpy ultilizando NP como conveção

In [1]:
import numpy as np

Definindo uma lista

In [2]:
minha_lista = [1, 2, 3]

In [3]:
minha_lista

[1, 2, 3]

Passando a lista como parametro do metodo array

In [4]:
np.array(minha_lista)

array([1, 2, 3])

Array de duas dimensões sendo uma lista de lista 

In [5]:
minha_matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Metodo arange do numpy. Criar uma lista de numeros sendo 0 o parametro de  inicio e 10 o parametro de final e 10 não estara incluso tendo um terceiro parametro não obrigatorio sendo ele ultilizado para definir o intervalo entre os valores a ser definido e se não definido será 1
Interesante de se ultilizar para criar sequencia de numeros 

In [7]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

Para criar matriz só de zeros

In [9]:
np.zeros(3)

array([0., 0., 0.])

todos os metodos podem ser asociados a alguma variavel 

In [10]:
arr = np.zeros(3)

In [11]:
arr

array([0., 0., 0.])

Passo uma tupla de 5 por 5 toda zerada

In [12]:
arr = np.zeros((5, 5))

In [13]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Tupla só de 1 3 por 3

In [14]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Para gerar uma matriz indentidade

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

lisnspace só muda o terceiro parametro onde ele define a quantidade de numeros que você quer ver

In [16]:
np.linspace(0, 10, 2)

array([ 0., 10.])

In [17]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

sub biblioteca chamada random com metodo rand numero aletorios de 0 a 1 com distibuição uniforme tendo eles a mesma probabilidade

In [18]:
np.random.rand(5)

array([0.51285162, 0.34359237, 0.56791711, 0.37358008, 0.28055525])

In [19]:
np.random.rand(5) * 100

array([24.48401254, 76.40783363, 16.63413655,  4.2184167 , 91.95897279])

gerar matriz com 3 dimensões com o rand

In [20]:
np.random.rand(5, 4, 3)

array([[[0.50389351, 0.08566857, 0.06111692],
        [0.80094094, 0.39635585, 0.11464052],
        [0.80326399, 0.66879701, 0.27144857],
        [0.19472693, 0.56406422, 0.7864641 ]],

       [[0.64975359, 0.70033616, 0.95649835],
        [0.2126999 , 0.71733732, 0.832656  ],
        [0.70836148, 0.57550088, 0.83061775],
        [0.54323218, 0.12740726, 0.35259312]],

       [[0.956271  , 0.98152372, 0.0644557 ],
        [0.03006818, 0.94216903, 0.87780882],
        [0.3426931 , 0.42278721, 0.48325226],
        [0.87793448, 0.76435913, 0.92933342]],

       [[0.53381365, 0.05583828, 0.61035542],
        [0.31947479, 0.39931384, 0.14591601],
        [0.06315986, 0.94771469, 0.78981623],
        [0.56337105, 0.89253725, 0.79525473]],

       [[0.79165749, 0.41610864, 0.22404973],
        [0.81326206, 0.97976306, 0.67245608],
        [0.07091561, 0.42428811, 0.54684185],
        [0.75190015, 0.77040039, 0.44274259]]])

randn numero aleatorios tirados de uma distribuição normal com media 0 e desvio padrão 1

In [21]:
np.random.randn(4)

array([-1.51791348, -0.53347414,  0.51047242,  1.14087917])

randint numero inteiros detre um intervalo sendo o segundo parametro não incluso 

In [22]:
np.random.randint(0, 100, 10)

array([91, 84, 42, 38,  2, 44, 82, 84,  4, 15])

In [23]:
np.random.rand(5) * 100

array([62.34165418, 63.70383933, 18.27858909, 98.44276621, 17.56505948])

round numero de casas decimais 

In [24]:
np.round(np.random.rand(5), 0)

array([1., 1., 0., 1., 0.])

In [25]:
np.round(np.random.rand(5) * 100, 0)

array([51., 45., 61., 52., 61.])

In [26]:
arr = np.random.rand(25)

In [27]:
arr

array([0.7572339 , 0.42291509, 0.34994568, 0.76127813, 0.91109736,
       0.65867046, 0.24888504, 0.32420097, 0.28391346, 0.30924698,
       0.81480748, 0.74020187, 0.36243941, 0.5507282 , 0.99652766,
       0.73424068, 0.03576145, 0.33849414, 0.25215894, 0.06979243,
       0.82216241, 0.0485474 , 0.52002303, 0.13945079, 0.52733743])

reshape muda o formato como exemplo ele muda um vetor de tamanho 25 para uma matriz de 5 por 5

In [28]:
arr.reshape((5, 5))

array([[0.7572339 , 0.42291509, 0.34994568, 0.76127813, 0.91109736],
       [0.65867046, 0.24888504, 0.32420097, 0.28391346, 0.30924698],
       [0.81480748, 0.74020187, 0.36243941, 0.5507282 , 0.99652766],
       [0.73424068, 0.03576145, 0.33849414, 0.25215894, 0.06979243],
       [0.82216241, 0.0485474 , 0.52002303, 0.13945079, 0.52733743]])

In [29]:
arr = arr.reshape((5, 5))

In [30]:
arr

array([[0.7572339 , 0.42291509, 0.34994568, 0.76127813, 0.91109736],
       [0.65867046, 0.24888504, 0.32420097, 0.28391346, 0.30924698],
       [0.81480748, 0.74020187, 0.36243941, 0.5507282 , 0.99652766],
       [0.73424068, 0.03576145, 0.33849414, 0.25215894, 0.06979243],
       [0.82216241, 0.0485474 , 0.52002303, 0.13945079, 0.52733743]])

parametro "shape" é ultilizado para verificar o tamanho do vetor ou matriz 

In [31]:
arr.shape

(5, 5)

metodo "max" é para ver o maior valor

In [32]:
arr.max()

0.9965276597783512

metodo 'min" encontrar menos valor

In [33]:
arr.min()

0.03576144749640364

"argmax" o indice que maior valor se encontra

In [34]:
arr.argmax()

14

"argmin" o indice que menos valor se encontra

In [35]:
arr.argmin()

16